[package]
name = "rust-url-wasm-demo"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
url = { path = "../rust-url/url" }
web-sys = { version = "0.3.66", features = ["Window", "Document", "HtmlInputElement"] }
yew = { version = "0.21.0", features = ["csr"] }
